name: livehorns
favicon: null
layout_spectrum: 0.5020156756509095
typography_spectrum: 0.5495299755129963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8894309755414724
  lightness: 0.38576729549095035
  saturation: 0.45144763635471463
  rhythmicContrast: 0.6871197542641312
purpose: []
